services:
  admin-service:
    build: .
    container_name: odontocare-admin
    ports:
      - "5000:5000"
    command: python odontocare/admin_app.py

  citas-service:
    build: .
    container_name: odontocare-citas
    ports:
      - "5001:5001"
    environment:
      - ADMIN_SERVICE_URL=http://admin-service:5000
    command: python odontocare/citas_app.py
    depends_on:
      - admin-service